# Generated by Django 2.2.3 on 2020-08-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200829_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateField(verbose_name='修改时间'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
